version: '3.3'
services:
  mysql:
    build:
      context: mysql
    container_name: local-envs_mysql
    command: --default-time-zone='+09:00' --default-authentication-plugin=mysql_native_password
    volumes:
      - ${HOME}/one/mysql/data:/var/lib/mysql
      - ${HOME}/one/mysql/log:/var/log/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=one
      - MYSQL_PASSWORD=one

  redis:
    build:
      context: redis
    container_name: local-envs_redis
    volumes:
      - ${HOME}/one/redis/data:/data
    ports:
      - "6379:6379"
  kafka:
    image: wurstmeister/kafka:2.13-2.7.1
    container_name: local-envs_kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"
  zookeeper:
    image: zookeeper:3.6.2
    container_name: local-envs_zookeeper
    ports:
      - "2181:2181"
  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: local-envs_kafdrop
    ports:
      - "9000:9000"
    environment:
      - KAFKA_BROKERCONNECT=kafka:29092
      - JVM_OPTS=-Xms256M -Xmx512M
    depends_on:
      - "kafka"
  rabbit:
    image: rabbitmq:3-management
    container_name: local-envs_rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
